export const NODE_TYPES = {
  START: 'start',
  END: 'end',
  LLM: 'llm',
  CODE: 'code',
  HTTP_REQUEST: 'http-request',
  IF_ELSE: 'if-else',
  TEMPLATE_TRANSFORM: 'template-transform',
  KNOWLEDGE_RETRIEVAL: 'knowledge-retrieval',
  VARIABLE_AGGREGATOR: 'variable-aggregator',
  ITERATION: 'iteration',
  VARIABLE_ASSIGNER: 'variable-assigner',
  PARAMETER_EXTRACTOR: 'parameter-extractor',
  QUESTION_CLASSIFIER: 'question-classifier',
  TOOL: 'tool',
  AGENT: 'agent',
  CONVERSATION_VARIABLES: 'conversation-variables',
  LIST_OPERATOR: 'list-operator',
  DOCUMENT_EXTRACTOR: 'document-extractor',
  LOOP: 'loop',
  ANSWER: 'answer',
  // Additional node types found in workflow-editor
  EXTRACT: 'extract',
  KB: 'kb',
  CONDITION: 'condition',
  DOCUMENT: 'document',
  SEARCH: 'search',
  RETRIEVAL: 'retrieval',
  CLASSIFIER: 'classifier',
  AGGREGATOR: 'aggregator',
  ASSIGNER: 'assigner',
} as const

export type NodeType = typeof NODE_TYPES[keyof typeof NODE_TYPES]
